apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-client
  labels:
    app: {{ .Values.containers.apiClient.podLabel }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.containers.apiClient.podLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.containers.apiClient.podLabel }}
    spec:
      securityContext: { }
      containers:
        - name: {{ .Values.containers.apiClient.name }}
          securityContext: { }
          image: "{{ .Values.image.apiClient }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ui
              containerPort: {{ .Values.containers.apiClient.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ui
          readinessProbe:
            httpGet:
              path: /
              port: ui
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
