#=============================
#= ENDPOINTS
#==============================
server:
  port: 8080
#=============================
#= SPRING CLOUD
#==============================
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#=============================
#= GATEWAY
#==============================
gateway:
  api:
    product-url: "host.docker.internal:8085"
    payment-url: "host.docker.internal:8082"
    abo-url: "host.docker.internal:8083"
    cart-url: "host.docker.internal:8084"